-- MySQL Script generated by MySQL Workbench

-- Wed Jun 28 16:03:21 2023

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering
SET
    @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- ----------------------------------------------------

-- Schema mydb

-- -----------------------------------------------------

-- -----------------------------------------------------

-- Table `mydb`.`user`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `DB_punk`.`user` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `login` VARCHAR(45) NOT NULL,
        `mdp` VARCHAR(200) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`phone`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `DB_punk`.`phone` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name_phone` VARCHAR(45) NOT NULL,
        `marque` VARCHAR(45) NOT NULL,
        `image` VARCHAR(145) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`caracteristique`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `DB_punk`.`caracteristique` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `nb_gear` INT NOT NULL,
        `steam` INT NOT NULL,
        `year` INT NOT NULL,
        `memoire` INT NOT NULL,
        `ecran` INT NOT NULL,
        `ram` INT NOT NULL,
        `phone_id` INT NOT NULL,
        PRIMARY KEY (`id`),
        CONSTRAINT `phone_id` FOREIGN KEY (`phone_id`) REFERENCES `DB_punk`.`phone` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO
    `user` (`login`, `mdp`)
VALUES (
        'admin',
        '$argon2id$v=19$m=65536,t=5,p=1$0spYLBIsc3/jmjj0m4xIpg$rl2DiQCdFkPJqociTEfc8BGKBmj2t4kkxehZIpHXMds'
    );

INSERT INTO
    `phone` (
        `name_phone`,
        `marque`,
        `image`
    )
VALUES (
        'Steampunk-O-Phone',
        'GearGadget',
        "http://localhost:5002/assets/images/Steampunk-O-Phone.jpg"
    ), (
        'Cog & Gears Communicator',
        'GearGadget',
        'http://localhost:5002/assets/images/Cog & Gears Communicator.jpg'
    ), (
        'BrassMaster 3000',
        'SteamWire',
        'http://localhost:5002/assets/images/BrassMaster 3000.jpg'
    ), (
        'SteamPunked Nexus',
        'SteamWire',
        'http://localhost:5002/assets/images/SteamPunked Nexus.jpg'
    ), (
        'Victorian Vaporizer',
        'ChronoComm',
        'http://localhost:5002/assets/images/Victorian Vaporizer.jpg'
    ), (
        'Clockwork Communicator',
        'ChronoComm',
        'http://localhost:5002/assets/images/Clockwork Communicator.jpg'
    ), (
        'The Steambeast',
        'MécaMobile',
        'http://localhost:5002/assets/images/The Steambeast.jpg'
    ), (
        "Gearsmith's Gilded Gadget",
        'MécaMobile',
        "http://localhost:5002/assets/images/Gearsmith's Gilded Gadget.jpg"
    ), (
        'The Steamfire Communicator',
        'VapeurTech',
        'http://localhost:5002/assets/images/The Steamfire Communicator.png'
    ), (
        'Steamberry 9000',
        'VapeurTech',
        'http://localhost:5002/assets/images/Steamberry 9000.png'
    );

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (2, 6, 1850, 3, true, 2, 1);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (4, 3, 1855, 5, true, 2, 1);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (1, 6, 1845, 3, true, 2, 2);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (6, 6, 1875, 6, true, 2, 2);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (2, 6, 1853, 3, true, 2, 3);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (6, 1, 1862, 3, true, 2, 3);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (2, 6, 1850, 3, true, 2, 4);

INSERT INTO
    `DB_punk`.`caracteristique` (
        `nb_gear`,
        `steam`,
        `year`,
        `memoire`,
        `ecran`,
        `ram`,
        `phone_id`
    )
VALUES (2, 6, 1850, 3, true, 2, 5);